Import CSV Usage in PyAdditive/Examples
ansys/pyadditive pull request #252
Opened 2024-02-12 22:18 UTC by safeerehman

- Update unit tests under `tests_*.py` to check for nan values when creating a simulation input. 
- Update pyadditive/examples to show the usage of import csv file into a study. 
- Update pyproject.toml/doc section

2024-02-13 00:04 UTC, pkrull-ansys requested changes
Bump the version in `pyproject.toml` and add a release note saying you updated the example.

2024-02-13 00:04 UTC, pkrull-ansys commented on tests/test_microstructure.py
> +
This is ok but there's a common idiom in python that uses the `setattr()` function to set an object's attribute by name. For example, the body of the test could be reduced to a couple lines.
```
with pytest.raises(ValueError, match=field + " must be a number"):
    setattr(input, field, float("nan"))
```
where `field` is a string containing the name of the attribute you're setting. You'd need to use `@pytest.mark.parametrize` and put the attribute names in a list. `field` would be the parameter passed into the test function.

2024-02-13 15:53 UTC, safeerehman commented on examples/11_advanced_parametric_study.py
> +
Yes, good point, I will update the append the error list to also include the number of duplicates removed.

2024-02-14 19:43 UTC, pkrull-ansys commented on src/ansys/additive/core/parametric_study/parametric_study.py
> +        drop_indices, error_list, duplicates = list(), list(), int()
```suggestion
        drop_indices, error_list = list(), list()
        duplicates = 0
```

2024-02-14 19:44 UTC, pkrull-ansys approved these changes
Approved with a suggestion.

2024-02-14 22:56 UTC, safeerehman commented
Closing due to unsigned commit
Duplicate PR at #259

2024-02-14 22:56 UTC, closed without merging